import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer} from "react-toastify";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Otak Atik",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.className} h-screen bg-tertiary text-white`}>
        {children}
        <ToastContainer 
        theme="dark"/>
      </body>
    </html>
  );
}
