-- CreateTable
CREATE TABLE "Account" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "type" STRING NOT NULL,
    "kelasFavorite" INT4[],
    "tutorFavorite" INT4[]
);

-- CreateTable
CREATE TABLE "kelas" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "nama" STRING NOT NULL,
    "kategori" STRING NOT NULL,
    "materi" STRING[],
    "spesifikasi" STRING,
    "metode" STRING[],
    "jadwal" STRING[],
    "ownerId" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "modul" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

-- CreateIndex
CREATE UNIQUE INDEX "Account_id_key" ON "Account"("id");

-- CreateIndex
CREATE UNIQUE INDEX "Account_email_key" ON "Account"("email");

-- CreateIndex
CREATE UNIQUE INDEX "kelas_id_key" ON "kelas"("id");

-- CreateIndex
CREATE UNIQUE INDEX "modul_id_key" ON "modul"("id");

-- AddForeignKey
ALTER TABLE "kelas" ADD CONSTRAINT "kelas_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
